name: Build and deploy front-page
on:
  push:
    branches: ["main"]
jobs:
  push-image:
    name: Build and push an image
    runs-on: ubuntu-20.04
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      PROJECT_ZONE: ${{ secrets.PROJECT_ZONE }}
      CLUSTER: ${{ secrets.CLUSTER }}
      REGISTRY: ${{ secrets.REGISTRY }}

      BASE_URL: ${{ secrets.BASE_URL }}
      MAP_KEY: ${{ secrets.MAP_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Google Auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GCP_SECRET }}"

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.PROJECT_ZONE }}

      - name: Configure Docker Client
        run: |-
          echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://$REGISTRY-docker.pkg.dev

      - name: Build Docker Image
        run: docker build --build-arg BASE_URL=$BASE_URL --build-arg MAP_KEY=$MAP_KEY . --tag front-page:latest          

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag front-page:latest $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/front-page:latest
          docker tag front-page:latest $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/front-page:$GITHUB_SHA
          docker push $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/front-page:latest
          docker push $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/front-page:$GITHUB_SHA

      - name: Deploy to GKE
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          envsubst < k8s/deployment.yml | kubectl apply -f - -n sima
          kubectl apply -f k8s/service.yml -n sima
          kubectl rollout status deployment/front-page -n sima
          kubectl get services -o wide -n sima